AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - 'dev/**/*'
    - 'resources/**/*'
    - 'temp.*'
    - 'vendor/**/*'
    - '.bundle/**/*'
    - '.git/**/*'
    - '.rubocop/**/*'
    - '*.rb'

Layout/HashAlignment:
  # EnforcedHashRocketStyle: table
  # EnforcedColonStyle: table
  Enabled: false

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Layout/LineLength:
  # Max: 120
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Naming/FileName:
  Exclude:
    - '**/Rakefile'

Naming/HeredocDelimiterNaming:
  ForbiddenDelimiters:
    - '(?:END|EOF)'

Naming/MethodParameterName:
  Enabled: false

Security/Eval:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: format, sprintf, percent
Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19
  Exclude:
    - '**/Rakefile'

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

# We've chosen to use Rubocop only for style, and not for
# "complexity" or "quality" checks.
#
# https://metaredux.com/posts/2020/05/26/rubocop-defaults-survey-results.html#sidenote

Metrics:
    Enabled: false
